[project]
name = "mkit-telegrambot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.10.1",
    "pyodbc>=5.2.0",
    "sqlalchemy>=2.0.43",
]
